apiVersion: apps/v1
kind: Deployment
metadata:
    name: test-autoscaler
spec:
    replicas: 2
    selector:
        matchLabels:
            service: nginx
    template:
        metadata:
            labels:
                service: nginx
                app: nginx
        spec:
            containers:
                - name: test-autoscaler
                  image: nginx
                  resources:
                      limits:
                          cpu: 300m
                          memory: 100Mi
                      requests:
                          cpu: 300m
                          memory: 100Mi