apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
    name: EKS-Cluster
    region: us-east-1
nodeGroup:
    - name: ng-1
      instanceType: t2.small
      desiredCapacity: 3
      ssh:
          publicKeyName: k8-labs
    - name: ng-mixed
      minSize: 3
      maxSize: 5
      instancesDistribution:
          maxPrice: 0.2
          instanceTypes: ["t2.small", "t3.small"]
          onDemandBaseCapacity: 0
          onDemandPercentageAboveBaseCapacity: 50
      ssh:
          publicKeyName: k8-labs
