apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
    name: dev-cluster
    region: us-east-1
    version: "1.20"
nodeGroups:
    - name: ng-1
      instanceType: t2.small
      minSize: 1
      maxSize: 4
      desiredCapacity: 1
      ssh:
          publicKeyName: live_keys
