apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
mountOptions:
  - debug

# Starting with k8s v1.11 the storageclass is automatically created
# there is no need to execute the "kubectl apply -f gp2..." command