apiVersion: v1
data:
  password: ZWtzLWNvdXJzZS1teXNxbC1wdw==
kind: Secret
metadata:
  creationTimestamp: "2021-08-05T17:05:29Z"
  name: mysql-pass
  namespace: ns-eks-course
  resourceVersion: "12529"
  selfLink: /api/v1/namespaces/ns-eks-course/secrets/mysql-pass
  uid: 533daf30-c817-46f3-91e6-83e125aa041e
type: Opaque
