apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: monitoring-cluster
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    minSize: 1
    maxSize: 4
    desiredCapacity: 3
    ssh:
      publicKeyName: Value
cloudWatch:
  clusterLogging:
    enableTypes: ["api", "audit", "authentication"] 