apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-locking-nfs-client-provisioner
  namespace: storage
subjects:
  - kind: ServiceAccount
    name: nfs-client-provisioner
    namespace: storage
roleRef:
  apiGroup:  rbac.authorization.k8s.io
  kind: Role
  name: leader-locking-nfs-client-provisioner