apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  namespace: storage
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - mountPath: /persistentvolumes
              name: nfs-client-root
          env:
            - name: PROVISIONER_NAME
              value: efs-storage
            - name: NFS_SERVER
              value: fs-a7f3a013.efs.us-east-1.amazonaws.com  # Change this!!!!!!  ----> fs-40386df4
            - name: NFS_PATH
              value: /
      volumes:
        - name: nfs-client-root
          nfs:
            server:  fs-a7f3a013.efs.us-east-1.amazonaws.com  # Change this!!!!!!  ----> fs-40386df4.efs.us-east-1.amazonaws.com
            path: /