apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-fargate
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 1

fargateProfiles:
  - name: fargatedemo
    podExecutionRoleARN: arn:aws:iam::225908212644:role/AmazonEKSFargatePodExecutionRole
    selectors:
      - namespace: fargatedemo
  - name: staging
    podExecutionRoleARN: arn:aws:iam::225908212644:role/AmazonEKSFargatePodExecutionRole
    selectors:
      - namespace: staging
        labels:
          env: staging
          checks: passed
availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c']