apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-single
  namespace: staging
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        env: staging
        checks: passed
    spec:
      containers:
        - name: redis-single
          image: redis
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 6379            
