apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-claim
  namespace: staging
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany