apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
        - name: foo
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/data"
              name: efs-pvc
      volumes:
        - name: efs-pvc
          persistentVolumeClaim:
            claimName: test-claim               