apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
    spec:
      containers:
        - name: bar
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/data"
              name: efs-pvc
      volumes:
        - name: efs-pvc
          persistentVolumeClaim:
            claimName: test-claim 