apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::942839947321:role/eksctl-dev-cluster-nodegroup-stan-NodeInstanceRole-1OYC3QQA1F04K
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::942839947321:user/k8s-cluster-admin
      username:  k8s-cluster-admin
      groups:
        - system:masters
    - userarn: arn:aws:iam::942839947321:user/prod-viewer
      username: prod-viewer
      groups:
        - prod-viewer-role
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-04T08:44:00Z"
  name: aws-auth
  namespace: kube-system 
  resourceVersion: "1512"
  uid: 276dd5f1-1736-489a-a1ff-76754db896bb