apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::225908212644:role/eksctl-EKS-Cluster-nodegroup-ng-1-NodeInstanceRole-LSGSV3AC03XV
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::225908212644:user/Ndomi
      username: Ndomi
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2021-08-05T15:22:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2158"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: fe587bf3-d966-4c4e-87c9-ae31310c2529
