apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: production
  name: prod-viewer-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"] # can be futher limited, e.g ["deployments", "replicasets", "pods"]
  verbs: ['get', "list", "watch"]